version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=242312359hH
      - POSTGRES_DB=bookmark_app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - nestjs
volumes:
  postgres:
networks:
  nestjs: